version: 1.0.{build}-{branch}

 # Test against this version of node.
environment:
  nodejs_version: "10"
skip_tags: true

 # Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # Pin the version of iedriver used
  - ps: choco install selenium-ie-driver --version 3.141.5
  - npm install

 # Post-install test scripts.
test_script:
  # Include installed iedriver on path
  - set PATH=C:\tools\selenium;%PATH%
  - echo %PATH%
  - node --version
  - npm --version
  - npm run build
  # Run test scaffolding
  - npx grunt testconfig fixture
  - appveyor-retry npx grunt connect test-webdriver:ie
  - npm run test:examples

 # Don't actually build.
build: off